### ISSUE TITLE
[solved] can't start spigot under ubuntu 16.04

### ISSUE THREAD

**Issue by BogusCurry** [MinecraftServerControl/mscs#143]
Hello ;D
I have a little problem, I will start the spigot server, but this messages comes by start from the command

mcuser@j303219:/opt/mscs/worlds/spigot$ mscs start spigot
Starting Minecraft Server: spigotCan't locate JSON.pm in @INC (you may need to install the JSON module) (@INC contains: /etc/perl /usr/local/lib/x86_64-linux-gnu/perl/5.22.1 /usr/local/share/perl/5.22.1 /usr/lib/x86_64-linux-gnu/perl5/5.22 /usr/share/perl5 /usr/lib/x86_64-linux-gnu/perl/5.22 /usr/share/perl/5.22 /usr/local/lib/site_perl /usr/lib/x86_64-linux-gnu/perl-base .) at -e line 2.
BEGIN failed--compilation aborted at -e line 2.
Error detecting the current Minecraft version.

What make I wrong ?

Have a nice Day ;D

Greetings
Bogus

**Comment by BogusCurry** [comment]
ok I have fixed .. 
then I have install the json moduls with 

sudo apt-get install libjson-perl

Have a nice Day ;D

**Comment by sandain** [comment]
Hi @BogusCurry.  I'm glad you were able to figure out the issue.  The [README](https://github.com/MinecraftServerControl/mscs/blob/master/README.md#prerequisites-for-installation) file already mentions the need for `libjson-perl`. The only thing I can see to do that might make this less of a problem would be to provide a better error message in the script itself. Right now the script [checks](https://github.com/MinecraftServerControl/mscs/blob/master/msctl#L1654) for all of the programs/packages listed in the Prerequisites section except `GNU Make` (which isn't a requirement of the script, it is just used for the easy install method), and `libjson-perl`.  Since libjson-perl is called from Perl, the check isn't as easy as `if [ ! -e libjson-perl ] ...`.

I'll try to come up with a simple way to check if this is installed so that we can through a more useful error.

**Comment by sandain** [comment]
I'm not currently in a position to test this right now, but here is a chunk of code that seems to function on my work computer:
```
perl -e 'use JSON;' > /dev/null 2>&1
if [ $? -ne 0 ]; then
  printf "ERROR: libjson-perl not found!\n"
  printf "Try installing this with:\n"
  printf "sudo apt-get install libjson-perl\n"
  exit 1
fi
```

**Comment by zanix** [comment]
This runs without error or output on my server that has MSCS working, but that just means I have `libjson-perl` installed.

I also tried on `Debian GNU/Linux 8.3 (jessie)`
```
ERROR: libjson-perl not found!
Try installing this with:
sudo apt-get install libjson-perl
```
 Seems ok to me

**Comment by sandain** [comment]
That is the result I would expect.  Thanks for testing @Zanix.  I'll just go ahead and send in the patch and test it when I get home.  I don't expect any fallout with this.

**Comment by sandain** [comment]
I just sent in commit 115b41c3b24b1a019c750e8e83e49d95bd0628b2.  Closing this issue.
