### ISSUE TITLE
Server update is bypassed with no user notification if previous update attempted in less that 1440 minutes prior (by default)

### ISSUE THREAD

**Issue by NetworkEng** [MinecraftServerControl/mscs#164]
Running mscs/msctl update will not update to latest minecraft server version 1.12. Latest version updated (on my host) is 1.11.2.  Apologies for the quick issue create with no additional troubleshooting, but will attempt to do that tonight when done with work.

**Comment by sandain** [comment]
Huh, it worked for me.  Try removing your `version_manifest.json` file, or at least check to make sure that 1.12 is listed as the latest release version in the file.

**Comment by NetworkEng** [comment]
Thanks Jason.  I checked /opt/mscs/version_manifest.json and it has a current timestamp (of when I manually ran the 'mscs update'), but the file was not the same as on the web at https://launchermeta.mojang.com/mc/game/version_manifest.json.

Found that this line:
`547:    find "$VERSIONS_JSON" -mmin +"$VERSIONS_DURATION" -delete
`
Along with this conditional:
`550:  if [ ! -s $VERSIONS_JSON ]; then
`
`551:    $WGET --no-use-server-timestamps -qO "$VERSIONS_JSON" "$MINECRAFT_VERSIONS_URL"
`
To be the culprit.  As you already know, it won't update if that version_manifest.json file already exists.  It seems the update was published some time this morning, after my daily cron job to update had run.

Yes, one can manually configure each world VERSIONS_DURATION to be less than one day for each world, but (to me) this is unexpected behavior.  I'd think that most users would expect a manual run of update to succeed if there is a newer version available, and not be bypassed if the update had been run in less than 1440 minutes.  For me, I wasn't aware that this restriction existed by default.

Perhaps this issue should be a feature request to consider changing the default behavior, or, add a command line option to "force" an update, bypassing the VERSIONS_DURATION limitation.

Thanks for your consideration.

-Matt

**Comment by NetworkEng** [comment]
In addition to a "force" command line option, would probably be good to inform the user that it did not attempt to update due to the last attempted update being less than the VERSIONS_DURATION timeframe, and to use the "force" option to bypass it.

**Comment by sandain** [comment]
Perhaps we should lower the VERSIONS_DURATION variable to something like 30 minutes -- a day is a long time and 30 minutes would do the job (10 minutes would probably be more than enough too).

I have no problem adding an error message, in fact it would probably be a good idea.  However, I believe that the code as it currently is would spit out the message if you have more than one world since the update function (`getCurrentMinecraftVersion`) is called for each world.  This would all have to be reworked to be smarter.

A `force` option is also probably a good idea.  However, due to the way the code is currently written, I don't think this would be a straight forward change either.

I'm extremely busy right now and don't have the time to really dive into this (but I could take the time to change the default value of VERSIONS_DURATION). If you know shell programming or want to learn, I would be happy to discuss patches with you.

**Comment by sandain** [comment]
I created a new branch and submitted RFC pull request #165 as a first pass at solving this issue.  Take a look and let me know what you think.

I have not added a `force-update` option or provided an error message if the update of the `versions_manifest.json` file is skipped, but that can still be added.

**Comment by sandain** [comment]
I just added the `force-update` option to that pull request.

**Comment by sandain** [comment]
With commit ee63109f740e5e2868aecee229634915435038ec, I think I have covered everything in this issue.  Let me know what you think.

**Comment by sandain** [comment]
Closing this issue with commit 0e03806516249dcffd5e19f0f2af5b125993d986.
