### ISSUE TITLE
version_manifest.json and duplicate world name issues

### ISSUE THREAD

**Issue by pixtop** [MinecraftServerControl/mscs#180]
Hi, I have 2 issues when I create a new world.
The first is I have the duplicate directory in directory of the world dir, I mean (/opt/mscs/worlds/test/test).
In that directory, there is nothing inside and when I delete it, it is recreated every time I start that server.
The second one is every time I start a server I'm notified by : 
"The cached copy of the version manifest is up to date.
Use the force-update option to ensure a new copy is downloaded."

What could I do to fix it ?
Thank you

**Comment by sandain** [comment]
Hi. I assume since you closed this you realized that neither is an issue. I'll go ahead and respond for the sake of helping someone else that has a similar question.
> The first is I have the duplicate directory in directory of the world dir, I mean (/opt/mscs/worlds/test/test).
> In that directory, there is nothing inside and when I delete it, it is recreated every time I start that server.

This is normal. `/opt/mscs/worlds/test` is the base folder, as far as MSCS is concerned, that all world files get installed to. Minecraft creates the `/opt/mscs/worlds/test/test` folder to hold some of the world specific files.

> The second one is every time I start a server I'm notified by :
> "The cached copy of the version manifest is up to date.
> Use the force-update option to ensure a new copy is downloaded."

This is also normal. All this message is telling you is that the version manifest is up to date. If you feel that the cached copy of the version manifest is out of date and this message is in error, it also tells you how to remedy the problem -- use the force-update option.
