### ISSUE TITLE
Overviewer Setup

### ISSUE THREAD

**Issue by shawnbyday** [MinecraftServerControl/mscs#181]
The overviewer setup seems a little bit out of date. Not due to mscs but due to some changes with Overviewer. Specifically with the GoogleMapsAPI key.

**Comment by sandain** [comment]
That doesn't surprise me. They were working on a new version that didn't require GoogleMaps if I recall correctly.  If you feel up to the task, I'll review patches to the README if that documentation needs updated.  The wiki should be editable by everyone if you want to touch the documentation there.  Otherwise, I'll take a look at this when I have some free time.

**Comment by shawnbyday** [comment]
You can find the following "work around" by @supernerdpp below:

I found this on the overviewer github issues page: [link](https://github.com/overviewer/Minecraft-Overviewer/issues/1308)

Hopefully this helps someone!

---

You have to get a key now, but anyone can get one from: https://developers.google.com/maps/documentation/javascript/get-api-key

Then in the index.html file, you have to make the following modification:
Change Line 14:
<script type="text/javascript" src="https://maps.google.com/maps/api/js?sensor=false"></script>

to:
<script type="text/javascript" src="https://maps.google.com/maps/api/js?key=<your key here>&sensor=false"></script>

Omitting <>

**Comment by shawnbyday** [comment]
I may take a look at it as well. I'm always shy of changing documentation because I'm never sure if I'm 100% correct or not. Fear of failure!

**Comment by sandain** [comment]
Fixed with patch by @Roflicide
