### ISSUE TITLE
Implement API for usage?

### ISSUE THREAD

**Issue by Aersaud** [MinecraftServerControl/mscs#184]
Not sure how to tag this as a question. Would it be possible to implement some kind of API I could use to create an admin panel ? Maybe something that spits out json data that can be retrieved from the server? Sorry if this has been mentioned or asked. Only thing I see related is the admin panel project that seems to be on hold.

**Comment by zanix** [comment]
Something like this was going to be worked on but everyone involved got too busy to keep working on it.
https://github.com/MinecraftServerControl/msc-gui was the start and used perl to spit out data to a web interface but it had to be on the same server. There were a few ideas on making an API just like you mentioned so that the admin interface could be anything, web, program, app, etc.

I wish I had time to help develop it but I have even less free time now than when we started the discussions and sandain put out a POC.

**Comment by sandain** [comment]
It would be easy to add json output to various functions like has been done for the query data (see the code for the [query-json](https://github.com/MinecraftServerControl/mscs/blob/master/msctl#L2750) command line option).

I adapted a dead project I had written in Perl years ago to serve as a proof-of-concept web-based admin panel for mscs and posted it to [mscs-gui](https://github.com/MinecraftServerControl/msc-gui) as @zanix mentioned.  It has a simple theme engine to allow for some customization, but it really needs more work for it to be useful. If you would like to take over that project, I could add you to the project and give you commit access. I don't care if any of my POC Perl code is used in the final product, but it would be nice to have an admin panel for mscs.  Let me know.

**Comment by Aersaud** [comment]
I'm not too familiar with Perl, I looked over your code but can't figure out how you are querying the server for information.

**Comment by sandain** [comment]
The `index.pl` script from msc-gui calls the main `mscs` script [here](https://github.com/MinecraftServerControl/msc-gui/blob/master/index.pl#L327), with the results of the call simply being returned as a string. The [load_theme](https://github.com/MinecraftServerControl/msc-gui/blob/master/index.pl#L274) subroutine uses this feature to run the query command so that it can replace tags like `<?msc_query_players?>` in the `world.xhtml` with a list of players.

**Comment by sandain** [comment]
I marked this issue as won't fix and will be closing the issue because this discussion should take place on the [msc-gui](https://github.com/MinecraftServerControl/msc-gui/issues) project instead.
