### ISSUE TITLE
Overviewer does not work with Minecraft 1.13

### ISSUE THREAD

**Issue by whakru** [MinecraftServerControl/mscs#200]
after launching the Overviewer (sudo mscs map)
mscs-maps-location = /var/www/SITE/public/map_m
It creates an empty folder with the name of the world and all. It remains empty ..
I did everything according to the documentation.

**Comment by sandain** [comment]
I just checked and Overviewer is not working on my server either. They must have changed something.  I'll try to look into it this weekend.

**Comment by whakru** [comment]
> I just checked and Overviewer is not working on my server either. They must have changed something. I'll try to look into it this weekend.

I figured out that the "Overviewer" does not support version 1.13 in which I am currently working.
Moved to mapcrafter ...

**Comment by sandain** [comment]
A [pull request](https://github.com/overviewer/Minecraft-Overviewer/pull/1471) has been submitted to Overviewer for supporting 1.13, but it doesn't look like it will be merged any time soon.

Although the Overviewer project still has a lot of user interest, it appears to have lost the interest of the majority of the developers.  [Mapcrafter](https://github.com/mapcrafter/mapcrafter) appears to have the same issue (see their README), although it already has full 1.13 support.

Perhaps for MSCS, the best thing we can do is make it easier to switch between mapping programs rather than hard coding one (currently Overviewer) in the script.  I'll try to look at the mapping code this weekend and see how easy it would be to make this happen.  @whakru, if you already have a patch, could you post it so that I can get an idea of what needs to happen?

**Comment by whakru** [comment]
> [Запрос тянуть](https://github.com/overviewer/Minecraft-Overviewer/pull/1471) был представлен Overviewer для поддержки 1.13, но это не похоже , что это будет объединено в ближайшее время.
> 
> Хотя проект Overviewer по-прежнему вызывает большой интерес пользователей, он, похоже, утратил интерес большинства разработчиков. [Mapcrafter,](https://github.com/mapcrafter/mapcrafter) похоже, имеет ту же проблему (см. Их README), хотя она уже имеет полную поддержку 1.13.
> 
> Возможно, для MSCS лучшее, что мы можем сделать, - это упростить переключение между программами отображения, а не жестко программировать одну (в настоящее время Overviewer) в сценарии. Я попытаюсь взглянуть на код сопоставления в эти выходные и посмотреть, как легко было бы это осуществить. @whakru , если у вас уже есть патч, не могли бы вы опубликовать его, чтобы я мог понять, что должно произойти?

The fact is that I left mapcraft separately.
I have my personal server for 3 players =) so I do not need difficulties =)

**Comment by sandain** [comment]
Let's leave this issue open for the time being.  I didn't have time this weekend to look into the change I mentioned above (making it easier to change mapping programs).

**Comment by sandain** [comment]
It looks like Overviewer merged the required changes and should now work with Minecraft 1.13.  I'm going to go ahead and close this issue, and open a new one asking for code to make it easier to change mapping programs.
