### ISSUE TITLE
no check for authbind

### ISSUE THREAD

**Issue by Nirgali42** [MinecraftServerControl/mscs#221]
If authbind is not installed, the script fails to start the server with an error but does not really explain the real reason behind the failure.

> The cached copy of the version manifest is up to date.
> Use the force-update option to ensure a new copy is downloaded.
> /usr/local/bin/msctl: line 1270: 11556 Terminated              nohup sh -c "tail -f --pid=\$$ $WORLD_DIR/console.in | {
>     $SERVER_COMMAND mscs-world=$1 > $WORLD_DIR/console.out 2>&1; kill \$$;
>   }" > /dev/null 2>&1
> Error starting the server: couldn't retrieve the server's process ID.

After wrapping msctl in bash -x, I see the line with the command executing java.  I ran it manually.  It starts with authbind as seen in the config file.  When I ran it, I saw that authbind was not installed.  I recommend adding a check for this command.  I spent two hours fighting this because I thought I did something wrong migrating from one host to another.

**Comment by sandain** [comment]
Hi @Nirgali42.

MSCS doesn't use `authbind`, in fact my test server doesn't even have it installed.  Since this is a local configuration issue, I don't see the need for adding another piece of prerequisite software.

However, maybe what you are asking for is for MSCS to parse the server command to make sure that it is executable.  Maybe something like this would work?
```
SERVER_COMMAND=$(getMSCSValue "$WORLD" "mscs-server-command" "$DEFAULT_SERVER_COMMAND")
COMMAND=(echo $SERVER_COMMAND | cut -d ' ' -f1)
if [ -z "$(which $COMMAND)" ]; then
  printf "Error reading the server command: couldn't find the program $COMMAND.\n"
  exit 1
fi
```

Actually, `cut` might not be enough for this since the user might have a space or tab at the beginining of the command.. So a `perl` one-liner might be needed here instead. Something like:
```
COMMAND=$(echo $SERVER_COMMAND | perl -ne 'print $1 if ($_ =~ /^\s*([\w\/]+)\s*/);')
```

Neither of these would check more than the first word in the command.. e.g., if the SERVER_COMMAND were `sudo ls`, this code would only make sure that `sudo` can be found, not `ls`.  This is a tough problem... When do you stop checking?

**Comment by sandain** [comment]
That perl regular expression assumes that program names include only `A..Z`, `a..z`, `0..9`, `_`, and `/`.  We would need to fix that to include all possible characters that a filename could have...  Of note, I already see I missed `.`.

Further complicating the issue would be spaces in a file name... This might make this idea completely intractable.

**Comment by sandain** [comment]
I'm going to label this as won't fix. But if you or anyone has suggestions on how to check that the command line is valid, feel free to reopen the issue.
