### ISSUE TITLE
Feature Request - List Ports

### ISSUE THREAD

**Issue by shawnbyday** [MinecraftServerControl/mscs#241]
Can you add a command that lists out all ports currently in use by mscs? Whether the world is running or not or enabled or not?

**Comment by sandain** [comment]
Try using the `mscs ls` command:
```
$ mscs ls
  alpha: 25567
  beta: 25568
  down: 25571
  lobby:
  over: 25590
  up: 25570
  world: 25566
  gamma: 25569 (disabled)
```

**Comment by sandain** [comment]
Is this what you needed @shawnbyday?  We could add code to output the data in a different manner if you need (e.g., json).  Note that my BungeeCord server does not report that it is using a port even though it is (25565 in this case), but all of the Vanilla Minecraft and Spigot servers report their ports.

**Comment by shawnbyday** [comment]
@sandain this is exactly what I needed. Maybe I misread the documentation but if I didn't and this information on what you get with ls isn't there maybe just add it to the docs and call it a day?

**Comment by zanix** [comment]
It's on the docs site but doesn't specify what the output is
https://minecraftservercontrol.github.io/docs/mscs/command-reference

```
ls <option>
  Display a list of worlds.
  Options:
    enabled   Display a list of enabled worlds, default.
    disabled  Display a list of disabled worlds.
    running   Display a list of running worlds.
    stopped   Display a list of stopped worlds.
  If no option, all available worlds are listed.
```

**Comment by zanix** [comment]
Maybe someone could add some example output for each command?
The documentation is here https://github.com/MinecraftServerControl/MinecraftServerControl.github.io

**Comment by Roflicide** [comment]
I added a section on the getting started section of the documentation called [listing worlds](https://minecraftservercontrol.github.io/docs/mscs/getting-started#listing-worlds). I also added a section on [enabling/disabling worlds](https://minecraftservercontrol.github.io/docs/mscs/getting-started#enablingdisabling-worlds) because I realized we haven't explicitly said what those commands do. Maybe I'll also update the command reference later with something brief that describes those commands. 

@shawnbyday Please let me know if the sections I added answers your questions. If you have any other questions or want something clarified, we'd be happy to help. Thanks!

**Comment by shawnbyday** [comment]
@Roflicide looks good to me, thanks! :)
