### ISSUE TITLE
Backup Times

### ISSUE THREAD

**Issue by shawnbyday** [MinecraftServerControl/mscs#249]
Hello!

I've been using mscs for quite some time now and I'm wondering if anyone else has reported backup times changing somewhat randomly?

I know as my world grows that my backup size grows but every world I've ever played using mscs the backup changes from about 30-40 seconds to a full 7 minutes with nothing in the world changing (loading new chunks/dimension etc). Is there something I'm missing in the way mscs backup functions that can help me decrease the time?

Thanks!

**Comment by sandain** [comment]
We use rdiff-backup to run backups.  I just checked my worlds, and all of them complete a backup in less than a minute, even my oldest world. 7 minutes seems off unless the world is _huge_.  Since rdiff-backup performs incremental backups, maybe you could try deleting the backup folder for the world and run a fresh backup (fresh backups take longer than the next). As long as you are running with the default configuration, backups are found in `/opt/mscs/backups/<world>/`.

**Comment by shawnbyday** [comment]
Thank you. This helped. The default is 30 days. I changed it to 10 and then deleted my backups folder and now it’s back to just a few seconds. Hopefully changing my default to 10 will help all of my worlds going forward.
