### ISSUE TITLE
Fabric Support

### ISSUE THREAD

**Issue by Infinidoge** [MinecraftServerControl/mscs#285]
Hello, mscs seems like an amazing tool to put to use running my servers.

However, looking through the documentation, I can't find any mention of support for [Fabric](https://fabricmc.net/). Is there a technical reason why Fabric isn't supported, or has it just not been added to the tool yet?

(Also this should probably have the question label added, I can't add it myself.)

**Comment by zanix** [comment]
Someone would need to figure out how it works on write up a guide similar to the other modded/alternate server docs https://minecraftservercontrol.github.io/docs/mscs/adjusting-world-server-properties.
My guess is that it's similar to Forge or SpigotMC

**Comment by sandain** [comment]
Hi @Infinidoge.  I imagine @Zanix is right here.  Try following the documentation for installing a Forge or SpigotMC server.  I doubt there are any specific changes that need to happen to get Fabric to work.

**Comment by Infinidoge** [comment]
@sandain Alright, good to know, thanks! After experimenting with that, would it help to submit a PR to add it to the documentation?

**Comment by sandain** [comment]
@Infinidoge: That would be fantastic. If you run into any issues, feel free to add more comments to this Issue for help.

I have finally finished my move across the country, and am in the process of unpacking my office. I should have my test server set back up in the near future (hopefully tonight). So, if  you hit a rough spot, I might be able to help replicate the issue by trying to install Fabric myself.

**Comment by Infinidoge** [comment]
After a bit of testing, installing Fabric is pretty similar to forge, but there is a key thing that should probably be noted.
The Fabric jar generates a config in the server folder to say which server jar it points to, so at the moment in testing it is pointing to a server jar in the world folder by default. (Which seems to be against the design intent of MSCS.)

I'll look into the possibility of setting a jar via the command it is run with, but there is a possibility that the config file will need to be edited to refer to the center `minecraft_server.$server_version.jar` file

**Comment by bitRAKE** [comment]
I don't know if this is the right way - just what I've done that worked:

* created a fabric folder in /server
* downloaded the fabric installer to /server/fabric
* execute installer, which creates: /server/fabric/fabric-server-launcher.jar
* rename launcher based on minecraft version
* `mscs create myWorld`
* modify `myWorld/mscs.properties`:
```
mscs-server-jar=fabric/fabric-server-launcher-21w19a.jar
mscs-server-url=
```
* create a link to minecraft server jar in myWorld directory.
* start world `mscs start myWorld`, this creates `fabric-server-launcher.properties`, modify it to point at link.

This allows me to have several versions of fabric/minecraft. Mapping errors will happen if an unexpected minecraft version is used with a configured fabric launcher. The working directory of the server jar is the world folder, so fabric reads the configuration from there.

Changing versions would only require changing the link and updating the `.properties` files.

**Comment by Poohblah** [comment]
I imported an existing Fabric world, which I was running previously on the same server without MSCS.  The only changes I needed to make were to edit these values in the world's `mscs.properties`:
* `mscs-server-location` - I pointed this to the directory containing `fabric-server-launch.jar`, `fabric-server-launcher.properties`, and my `mods` dir.
* `mscs-server-jar` - I pointed this to the name of the fabric launcher jar (`fabric-server-launch.jar`) within the directory given to `mscs-server-location`.

Otherwise, seems to be working quite well with no other customizations needed for Fabric.  So basically my experience lines up with @bitRAKE's.  I probably could've moved the fabric launcher jar to `/opt/mscs/server` like bitRAKE did instead, but personally I thought it was easier to keep the existing directory structure of my imported world and update the MSCS configuration to match, rather than the other way around.
